#!/bin/bash
# Checkpoint/Resume Demo Script
# This script demonstrates the checkpoint/resume workflow

set -e  # Exit on error

echo "═══════════════════════════════════════════════════════════════"
echo "  SPHCode Checkpoint/Resume Demonstration"
echo "═══════════════════════════════════════════════════════════════"
echo ""

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Check we're in the right directory
if [ ! -f "build/sph1d" ]; then
    echo "Error: Please run this script from the SPHCode root directory"
    echo "Expected: /Users/guo/OSS/sphcode"
    exit 1
fi

cd build

echo -e "${BLUE}Step 1: Understanding Checkpoint Configuration${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Checkpoint settings in config JSON:"
echo '  "enableCheckpointing": true      # Enable auto-save'
echo '  "checkpointInterval": 0.05       # Save every 0.05 time units'
echo '  "checkpointMaxKeep": 3           # Keep only last 3 checkpoints'
echo '  "checkpointOnInterrupt": true    # Save on Ctrl+C'
echo ""
read -p "Press Enter to continue..."
echo ""

echo -e "${BLUE}Step 2: Understanding Resume Configuration${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Resume settings in config JSON:"
echo '  "resumeFromCheckpoint": true'
echo '  "resumeCheckpointFile": "output/run_XYZ/checkpoints/checkpoint_t5.0.chk"'
echo ""
echo "The checkpoint file path must point to an actual .chk file created during"
echo "a previous run. The simulation will load the particle state and continue"
echo "from that exact time point."
echo ""
read -p "Press Enter to continue..."
echo ""

echo -e "${BLUE}Step 3: Checkpoint File Structure${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "When you run with checkpointing enabled, the output structure is:"
echo ""
echo "output/"
echo "└── run_20251101_143000/          # Timestamped run directory"
echo "    ├── checkpoints/               # Checkpoint subdirectory"
echo "    │   ├── checkpoint_t0.050000.chk"
echo "    │   ├── checkpoint_t0.100000.chk"
echo "    │   └── checkpoint_t0.150000.chk"
echo "    └── output_00000.dat          # Regular output files"
echo ""
echo "Checkpoint files contain:"
echo "  • Binary particle data (position, velocity, mass, etc.)"
echo "  • Simulation parameters (JSON-encoded)"
echo "  • SHA-256 checksum for integrity verification"
echo "  • Metadata (time, timestep, particle count)"
echo ""
read -p "Press Enter to continue..."
echo ""

echo -e "${BLUE}Step 4: Workflow Example${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo -e "${YELLOW}Scenario: Run simulation, interrupt it, then resume${NC}"
echo ""
echo "1️⃣  Initial run with checkpointing:"
echo "    ./sph1d shock_tube config.json"
echo ""
echo "    Output during run:"
echo "    > Saving checkpoint at t=0.050000"
echo "    > Checkpoint saved: output/run_20251101_143000/checkpoints/checkpoint_t0.050000.chk"
echo "    > Saving checkpoint at t=0.100000"
echo "    > ^C  (User presses Ctrl+C)"
echo "    > *** Interrupt signal received (Ctrl+C) ***"
echo "    > Saving interrupt checkpoint at t=0.123456"
echo "    > Checkpoint saved: output/run_20251101_143000/checkpoints/checkpoint_t0.123456.chk"
echo "    > Resume with: \"resumeFromCheckpoint\": true"
echo ""
echo "2️⃣  Update config_resume.json with actual checkpoint path:"
echo '    "resumeCheckpointFile": "output/run_20251101_143000/checkpoints/checkpoint_t0.123456.chk"'
echo ""
echo "3️⃣  Resume simulation:"
echo "    ./sph1d shock_tube config_resume.json"
echo ""
echo "    Output:"
echo "    > Loading checkpoint from: output/run_20251101_143000/checkpoints/checkpoint_t0.123456.chk"
echo "    > Checkpoint loaded successfully"
echo "    >   Particles: 400"
echo "    >   Time: 0.123456"
echo "    > Resuming simulation from t=0.123456..."
echo "    > Saving checkpoint at t=0.150000"
echo "    > Simulation complete at t=0.200000"
echo ""
read -p "Press Enter to continue..."
echo ""

echo -e "${BLUE}Step 5: Advanced Use Cases${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo -e "${GREEN}Use Case 1: Initial Conditions from Checkpoint${NC}"
echo "Create relaxed equilibrium state, then use as initial conditions:"
echo ""
echo "# Run relaxation simulation"
echo "./sph1d disk_relax relax_config.json  # Runs to t=100, creates checkpoint"
echo ""
echo "# Use checkpoint as initial state for evolution"
echo "# In evolution_config.json:"
echo '  "initialConditionsFile": "output/run_XYZ/checkpoints/checkpoint_t100.0.chk"'
echo ""
echo "./sph1d disk_evolve evolution_config.json"
echo ""
echo ""
echo -e "${GREEN}Use Case 2: Long-Running Simulations${NC}"
echo "For very long simulations, use checkpointing to protect against crashes:"
echo ""
echo '  "checkpointInterval": 50.0    # Save every 50 time units'
echo '  "checkpointMaxKeep": 10       # Keep last 10 checkpoints'
echo ""
echo "If simulation crashes or machine loses power, resume from last checkpoint!"
echo ""
echo ""
echo -e "${GREEN}Use Case 3: Parameter Studies${NC}"
echo "Run from same initial state with different parameters:"
echo ""
echo "# Create initial state"
echo "./sph1d setup setup_config.json  # Creates checkpoint at t=10"
echo ""
echo "# Run multiple simulations from same checkpoint"
echo "./sph1d test run1_config.json  # Uses checkpoint_t10.chk with alpha=0.5"
echo "./sph1d test run2_config.json  # Uses checkpoint_t10.chk with alpha=1.0"
echo "./sph1d test run3_config.json  # Uses checkpoint_t10.chk with alpha=2.0"
echo ""
read -p "Press Enter to continue..."
echo ""

echo -e "${BLUE}Step 6: Troubleshooting${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo -e "${YELLOW}Common Issues and Solutions:${NC}"
echo ""
echo "❌ Error: 'Cannot open checkpoint file'"
echo "   Solution: Check file path is correct and file exists"
echo "   Example: ls output/*/checkpoints/*.chk"
echo ""
echo "❌ Error: 'Checkpoint validation failed'"
echo "   Solution: File is corrupted, try different checkpoint from same run"
echo ""
echo "❌ Error: 'Dimension mismatch'"
echo "   Solution: Checkpoint from sph1d cannot be used with sph2d/sph3d"
echo ""
echo "❌ Warning: 'Checkpoint overhead > 5%'"
echo "   Solution: Increase checkpointInterval for better performance"
echo ""
read -p "Press Enter to continue..."
echo ""

echo -e "${BLUE}Step 7: Example Files Created${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "The following example files have been created for you:"
echo ""
echo "📄 example_checkpoint_config.json"
echo "   Template config with checkpointing enabled"
echo "   Use this as starting point for your simulations"
echo ""
echo "📄 example_resume_config.json"
echo "   Template config for resuming from checkpoint"
echo "   Update the resumeCheckpointFile path with your actual checkpoint"
echo ""
echo "📚 CHECKPOINT_TUTORIAL.md"
echo "   Complete tutorial with examples and best practices"
echo ""
echo "📚 CHECKPOINT_README.md"
echo "   Quick reference guide"
echo ""
echo "📚 docs/CHECKPOINT_USER_GUIDE.md"
echo "   Comprehensive user documentation"
echo ""
read -p "Press Enter to finish..."
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo -e "${GREEN}✓ Demonstration Complete!${NC}"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Next steps:"
echo "  1. Read CHECKPOINT_TUTORIAL.md for detailed examples"
echo "  2. Try running a simulation with checkpointing enabled"
echo "  3. Practice interrupting and resuming a simulation"
echo ""
echo "For help, see:"
echo "  • CHECKPOINT_README.md - Quick reference"
echo "  • docs/CHECKPOINT_USER_GUIDE.md - Full documentation"
echo ""
echo "Happy simulating! 🚀"
echo ""
